http://127.0.0.1:8000/api/users

###

http://127.0.0.1:8000/api/users/3

### // category

http://127.0.0.1:8000/api/categories

###

http://127.0.0.1:8000/api/categories/3

###  // subcategory

http://127.0.0.1:8000/api/subcategories

###

http://127.0.0.1:8000/api/subcategories/3

### // order

http://127.0.0.1:8000/api/orders

###

http://127.0.0.1:8000/api/orders/3

### // product

http://127.0.0.1:8000/api/products

###

http://127.0.0.1:8000/api/products/3






